version: "3.6"

volumes:
  shared-workspace:
    name: "hadoop-distributed-file-system"
    driver: local

services:

  jupyterlab:
    image: jupyterlab
    container_name: jupyterlab
    ports:
      - 8888:8888
      - 4040:4040
    volumes:
      - shared-workspace:/opt/workspace
    networks:
      spark-cluster:
        ipv4_address: 10.0.2.8
    extra_hosts:
      - "spark-master:10.0.2.2"
      - "spark-worker-1:10.0.2.3"
      - "spark-worker-2:10.0.2.4"
      - "postgres:10.0.2.5"


  spark-master:
    image: spark-master
    container_name: spark-master
    ports:
      - 8080:8080
      - 7077:7077
    volumes:
      - shared-workspace:/opt/workspace
    networks:
      spark-cluster:
        ipv4_address: 10.0.2.2
    extra_hosts:
      - "jupyterlab:10.0.2.8"
      - "spark-worker-1:10.0.2.3"
      - "spark-worker-2:10.0.2.4"
      - "postgres:10.0.2.5"


  spark-worker-1:
    image: spark-worker
    container_name: spark-worker-1
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=2048m
    ports:
      - 8081:8081
    volumes:
      - shared-workspace:/opt/workspace
    depends_on:
      - spark-master
    networks:
      spark-cluster:
        ipv4_address: 10.0.2.3
    extra_hosts:
      - "jupyterlab:10.0.2.8"
      - "spark-master:10.0.2.2"
      - "spark-worker-2:10.0.2.4"
      - "postgres:10.0.2.5"

  spark-worker-2:
    image: spark-worker
    container_name: spark-worker-2
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=2048m
    ports:
      - 8082:8081
    volumes:
      - shared-workspace:/opt/workspace
    depends_on:
      - spark-master
    networks:
      spark-cluster:
        ipv4_address: 10.0.2.4
    extra_hosts:
      - "jupyterlab:10.0.2.8"
      - "spark-master:10.0.2.2"
      - "spark-worker-1:10.0.2.3"
      - "postgres:10.0.2.5"

  postgres:
    container_name: postgres
    image: postgres:14.5-bullseye
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminadmin
      PGDATA: /data/postgres
    volumes:
       - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always
    networks:
      spark-cluster:
        ipv4_address: 10.0.2.5
    extra_hosts:
      - "jupyterlab:10.0.2.8"
      - "spark-master:10.0.2.2"
      - "spark-worker-1:10.0.2.3"
      - "spark-worker-2:10.0.2.4"

networks:
 spark-cluster:
  ipam:
   driver: default
   config:
   - subnet: 10.0.2.0/24
...